#!/bin/bash
# Regenerate nginx gw routes (lua + locations) from sites.json and refresh status.
set -euo pipefail

SITES="${SITES_JSON:-/var/www/center-portal/sites.json}"
GW_CONF="${GW_CONF:-/www/server/panel/vhost/nginx/center-portal-gw.inc}"
ROUTES_LUA="${ROUTES_LUA:-/etc/nginx/lua/center-gw-routes.lua}"
STATUS_SH="${STATUS_SH:-/opt/center-portal/center-portal-status.sh}"
NGINX_RELOAD="${NGINX_RELOAD:-/etc/init.d/nginx reload}"

command -v jq >/dev/null 2>&1 || { echo "jq required" >&2; exit 1; }
[ -f "$SITES" ] || { echo "missing $SITES" >&2; exit 1; }

TMP="$(mktemp)"
TMP_LUA="$(mktemp)"

{
  echo "-- Generated by center-portal-sync — do not edit"
  echo "return {"
  jq -c '.sites[]?' "$SITES" | while read -r row; do
    id="$(echo "$row" | jq -r '.id // empty')"
    port="$(echo "$row" | jq -r '.luci_port // empty')"
    host="$(echo "$row" | jq -r '.luci_host // "192.168.9.1"')"
    [ -n "$id" ] || continue
    [ -n "$port" ] || continue
    case "$id" in
      *[!a-zA-Z0-9_-]*)
        echo "skip invalid site id: $id" >&2
        continue
        ;;
    esac
    echo "  [\"${id}\"] = { port = ${port}, host = \"${host}\" },"
  done
  echo "}"
} >"$TMP_LUA"

mv -f "$TMP_LUA" "$ROUTES_LUA"
chmod 644 "$ROUTES_LUA"

cat >"$TMP" <<'NGINX'
# Generated by center-portal-sync — LuCI under /home/gw/<site_id>/ (prefix ^~ beats /home/ alias)
set $gw_port "";
set $gw_host "";
set $gw_pub_prefix "";
set $gw_backend_path "";

location ^~ /home/gw/ {
    access_by_lua_file /etc/nginx/lua/center-portal-gw-handler.lua;
    proxy_pass https://127.0.0.1:$gw_port$gw_backend_path$is_args$args;
    proxy_ssl_verify off;
    proxy_http_version 1.1;
    proxy_set_header Host $gw_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect ~^https?://[^/]+/(.*)$ https://$http_host$gw_pub_prefix$1;
    proxy_redirect ~^/(.*)$ https://$http_host$gw_pub_prefix$1;
    proxy_buffering on;
    sub_filter_once off;
    sub_filter_types text/html text/css application/javascript application/json;
    sub_filter 'href="/luci-static/' 'href="${gw_pub_prefix}luci-static/';
    sub_filter 'src="/luci-static/' 'src="${gw_pub_prefix}luci-static/';
    sub_filter 'action="/cgi-bin/' 'action="${gw_pub_prefix}cgi-bin/';
    sub_filter '"/cgi-bin/' '"${gw_pub_prefix}cgi-bin/';
    sub_filter 'href="/"' 'href="${gw_pub_prefix}cgi-bin/luci/"';
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}

# LuCI HTML still references /luci-static/ at site root — use center_gw cookie
location ^~ /cgi-bin/ {
    access_by_lua_file /etc/nginx/lua/center-portal-gw-proxy.lua;
    proxy_pass https://127.0.0.1:$gw_port$request_uri;
    proxy_ssl_verify off;
    proxy_http_version 1.1;
    proxy_set_header Host $gw_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect ~^https?://[^/]+/(.*)$ https://$http_host$gw_pub_prefix$1;
    proxy_redirect ~^/(.*)$ https://$http_host$gw_pub_prefix$1;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}

location ^~ /luci-static/ {
    access_by_lua_file /etc/nginx/lua/center-portal-gw-proxy.lua;
    proxy_pass https://127.0.0.1:$gw_port$request_uri;
    proxy_ssl_verify off;
    proxy_http_version 1.1;
    proxy_set_header Host $gw_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}
NGINX

mv -f "$TMP" "$GW_CONF"
chmod 644 "$GW_CONF"

if [ -x "$STATUS_SH" ]; then
  "$STATUS_SH"
fi

if nginx -t 2>/dev/null; then
  $NGINX_RELOAD
  echo "nginx reloaded; gw -> $GW_CONF routes -> $ROUTES_LUA"
else
  echo "nginx -t failed; gw routes/lua updated but nginx not reloaded:" >&2
  nginx -t 2>&1 >&2 || true
  exit 1
fi
