#!/bin/sh
# Bandix eBPF traffic stats require flow offloading disabled.

uci -q set firewall.@defaults[0].flow_offloading='0'
uci -q set firewall.@defaults[0].flow_offloading_hw='0'
uci -q commit firewall

exit 0
