#!/bin/sh /etc/rc.common
# On-demand only: do NOT enable at boot. Use upload-env / upload-teardown manually or via LuCI.
# START is unset so procd will not auto-run this without explicit enable (avoid permanent /dat bind).

start() {
	[ -x /usr/libexec/lede-firmware-upload-env.sh ] && \
		/usr/libexec/lede-firmware-upload-env.sh
}

stop() {
	[ -x /usr/libexec/lede-firmware-upload-teardown.sh ] && \
		/usr/libexec/lede-firmware-upload-teardown.sh
}
