#!/bin/sh /etc/rc.common
# Snapshot hardware inventory once per boot (background).

START=99

start() {
	[ -x /usr/libexec/lede-hwinfo ] || return 0
	( /usr/libexec/lede-hwinfo >/dev/null 2>&1 ) &
}

boot() {
	start
}

reload() {
	start
}
