#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	[ -x /usr/libexec/lede-wan-https ] && /usr/libexec/lede-wan-https >/dev/null 2>&1 || true
}

reload_service() {
	start_service
}

service_triggers() {
	procd_add_reload_trigger lede-remote
}
